# Generated by Django 5.1.15 on 2026-09-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from imported CSV if provided', max_length=100, null=True)),
                ('name', models.CharField(help_text='Full name of invitee', max_length=255)),
                ('phone', models.CharField(db_index=True, help_text='Phone number (E.164 or standardized format)', max_length=32)),
                ('email', models.EmailField(db_index=True, help_text='Invitee email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'email'], name='idx_invitee_phone_email')],
            },
        ),
    ]
