# Generated by Django 5.1.15 on 2026-09-14 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('provider_call_id', models.CharField(blank=True, db_index=True, help_text='Unique call identifier generated by the calling provider', max_length=128)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('rsvp_outcome', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('UNDECIDED', 'Undecided')], default='PENDING', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the call in seconds')),
                ('error_code', models.CharField(blank=True, help_text='Machine-readable error code if call failed (e.g. TIMEOUT, BUSY, NETWORK_ERROR)', max_length=64)),
                ('error_message', models.TextField(blank=True, help_text='Human-readable description of error or failure reason')),
                ('transcript_summary', models.TextField(blank=True, help_text='Summary of AI agent conversation with invitee')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='campaigns.campaigninvitee')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['campaign_invitee', 'attempt_number'], name='idx_attempt_campinv_num')],
            },
        ),
    ]
