# Generated by Django 5.1.15 on 2026-09-14 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Campaign name, e.g. Annual Business Meet — RSVP', max_length=255)),
                ('event_name', models.CharField(help_text='Event name, e.g. GlobalVox Annual Business Meet', max_length=255)),
                ('event_date', models.DateField(help_text='Scheduled date of the event')),
                ('event_location', models.CharField(help_text='Event location, e.g. Ahmedabad', max_length=255)),
                ('objective', models.TextField(blank=True, default='AI voice agent contacts invitees to collect RSVP responses.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('UNDECIDED', 'Undecided')], db_index=True, default='PENDING', max_length=20)),
                ('call_status', models.CharField(choices=[('NOT_ATTEMPTED', 'Not Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NOT_ATTEMPTED', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes or summary captured from AI voice conversation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_invitees', to='campaigns.campaign')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to='invitees.invitee')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['campaign', 'rsvp_status'], name='idx_camp_rsvp_status'), models.Index(fields=['campaign', 'call_status'], name='idx_camp_call_status')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'invitee'), name='unique_campaign_invitee')],
            },
        ),
    ]
