from django.db import models
from apps.campaigns.models import CampaignInvitee, RSVPStatus

class CallAttemptStatus(models.TextChoices):
    IN_PROGRESS = 'IN_PROGRESS', 'In Progress'
    COMPLETED = 'COMPLETED', 'Completed'
    FAILED = 'FAILED', 'Failed'

class CallAttempt(models.Model):
    """
    Audit log of each individual call attempt made by the calling provider to an invitee.
    """
    campaign_invitee = models.ForeignKey(
        CampaignInvitee,
        on_delete=models.CASCADE,
        related_name='call_attempts'
    )
    attempt_number = models.PositiveIntegerField(default=1)
    provider_call_id = models.CharField(
        max_length=128,
        blank=True,
        db_index=True,
        help_text="Unique call identifier generated by the calling provider"
    )
    status = models.CharField(
        max_length=20,
        choices=CallAttemptStatus.choices,
        default=CallAttemptStatus.IN_PROGRESS,
        db_index=True
    )
    rsvp_outcome = models.CharField(
        max_length=20,
        choices=RSVPStatus.choices,
        default=RSVPStatus.PENDING,
        blank=True
    )
    duration_seconds = models.PositiveIntegerField(
        default=0,
        help_text="Duration of the call in seconds"
    )
    error_code = models.CharField(
        max_length=64,
        blank=True,
        help_text="Machine-readable error code if call failed (e.g. TIMEOUT, BUSY, NETWORK_ERROR)"
    )
    error_message = models.TextField(
        blank=True,
        help_text="Human-readable description of error or failure reason"
    )
    transcript_summary = models.TextField(
        blank=True,
        help_text="Summary of AI agent conversation with invitee"
    )
    started_at = models.DateTimeField(auto_now_add=True)
    ended_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-started_at']
        indexes = [
            models.Index(fields=['campaign_invitee', 'attempt_number'], name='idx_attempt_campinv_num'),
        ]

    def __str__(self):
        return f"Attempt #{self.attempt_number} for {self.campaign_invitee.invitee.name} [{self.status}]"
